### PR TITLE
Completion script for aws-vault

### LINKED ISSUE #20: Merge reegnz/aws-vault-zsh-plugin zsh completion script
Would you be open to merging [my aws-vault completion script](https://github.com/reegnz/aws-vault-zsh-plugin)? I'd be glad to have that in a plugin that's more popular than mine, so that other people benefit from it as well. :)

### PR DESCRIPTION
**Pull request by reegnz**
Fixes #20

### CODE REVIEW

**Comment by reegnz** [comment]
I have taken the completion script in https://github.com/reegnz/aws-vault-zsh-plugin and updated it to work with the latest aws-vault version.

**Comment by blimmer** [comment]
Thanks @reegnz - this is great. One question - do you know how we can unify the current completion (https://github.com/blimmer/zsh-aws-vault/blob/3d5ad1ebfc12f91b157f7bf2a38027fc4f48bb76/_av_completion) with your improved completion script from this PR?

I'm not super-familiar with how completions work in zsh. Basically, what I'd love to see is how we could update the plugin file (https://github.com/blimmer/zsh-aws-vault/blob/main/zsh-aws-vault.plugin.zsh) to delegate to your completions.

I was toying around with this locally and I think we want something like this:

```bash
function avl() {
  aws-vault login $@
}
compdef avl=aws-vault
```

That's close, but we really want to alias the completions of `avl` to `aws-vault login` and I'm not sure how to do that. @reegnz, do you know how to do this

Thanks again for taking time to contribute!

**Comment by reegnz** [comment]
I put it in a script called `_aws_vault` as that's a common way of shipping completion scripts for zsh.
The great thing about zsh is it's smart about aliases, so if you do `alias avl=aws-vault login` completion will still work, without having to compdef.

So I'll have a look in replacing the avl function with a plain alias.

**Comment by reegnz** [comment]
So `avl`, `avll`, `ave` can be replaced with a plain alias. `avsh` and `avli` are a bit harder nut to crack, I think for those it makes more sense to keep a separate completion file (as they're not possible to replace with just an alias, they're actually new commands built on top of `aws-vault`).

**Comment by reegnz** [comment]
@blimmer I did some changes, now all aliases (except for avsh and avli) are using the _aws_vault completion.
I think given that avsh and avli are new commands, it's much harder for them to adopt the completion of _aws_vault, so I didn't take a run on doing those.

**Comment by blimmer** [comment]
@reegnz - this is great. Thank you so much for taking the time to merge in your work to this repo!

**Pull request merged**
